# Generated by Django 6.0.4 on 2026-04-11 12:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulaire', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('courant', 'Compte Courant'), ('epargne', 'Compte Épargne'), ('professionnel', 'Compte Professionnel')], max_length=20)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('devise', models.CharField(default='XAF', max_length=3)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('ferme', 'Fermé')], default='actif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('transfert', 'Transfert')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('statut', models.CharField(choices=[('en_attente', 'En Attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué')], default='en_attente', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='comptes.compte')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
